name: MagicPod-TestRail Integration
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests zipfile36
      
      - name: Prepare TestRail test plan
        env:
          TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
          TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_TESTPLAN_JSON_FILENAME: testplan.json
        run: python testrail_prepare.py
      
      - name: Download MagicPod API client
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
        run: |
          echo "🚀 Starting MagicPod client download..."
          python download_magicpod_client.py
          
          # Verify download success
          if [ -d "magicpod-api-client" ]; then
            echo "✅ MagicPod client downloaded successfully"
            echo "📁 Contents:"
            ls -la magicpod-api-client/
          else
            echo "❌ MagicPod client download failed"
            exit 1
          fi
        continue-on-error: false
      
      - name: Run MagicPod tests
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
          MAGICPOD_ORGANIZATION_NAME: ${{ secrets.MAGICPOD_ORGANIZATION_NAME }}
          MAGICPOD_PROJECT_NAME: ${{ secrets.MAGICPOD_PROJECT_NAME }}
          MAGICPOD_TEST_SETTING_ID: ${{ secrets.MAGICPOD_TEST_SETTING_ID }}
          MAGICPOD_ENVIRONMENT: ${{ secrets.MAGICPOD_ENVIRONMENT }}
          MAGICPOD_BROWSER: ${{ secrets.MAGICPOD_BROWSER }}
          TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
          TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
          TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
          TESTRAIL_TESTPLAN_JSON_FILENAME: testplan.json
        run: |
          echo "🧪 Starting MagicPod test execution..."
          python run_magicpod.py
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            testplan.json
            *.log
            magicpod-api-client/
          retention-days: 30
      
      - name: Debug information (on failure)
        if: failure()
        run: |
          echo "🔍 Debug Information:"
          echo "Working directory contents:"
          ls -la
          echo ""
          echo "Environment variables (non-sensitive):"
          env | grep -E "^(GITHUB_|RUNNER_)" | sort
          echo ""
          if [ -f "testplan.json" ]; then
            echo "TestRail plan content:"
            cat testplan.json
          fi